version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: express_nginx
        ports:
          - 80:80
        volumes:
          - .docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
          - ./express:/var/www
        depends_on:
          - node
        networks: 
          - nginx-network

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: express_mysql
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: express
            MYSQL_USER: express
            MYSQL_PASSWORD: express
        networks: 
          - mysql-network
    
    mongo:
        image: mongo:latest
        container_name: express_mongo
        volumes:
          - mongodata:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: express
        ports:
            - 27017:27010
        entrypoint: ['/usr/bin/mongod', '--auth']
        networks:
          - mongo-network
    
    node:
        image: node:latest
        container_name: express_node
        volumes: 
            - ./express:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install && npm start'
        environment:
            - maildev_host=laravel_maildev
            - PORT=8000
           # - DEBUG=express:* Only for debug
        depends_on:
            - maildev
            - mysql
            - mongo
        networks:
          - mail-network
          - nginx-network
          - mongo-network
          - mysql-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: express_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        networks: 
          - mysql-network

    maildev:
        image: djfarrelly/maildev
        container_name: express_maildev
        ports:
          - 8001:80
        networks: 
          - mail-network

volumes:
    dbdata:
      driver: local
    mongodata:
      driver: local

networks: 
    mongo-network:
      driver: bridge
    nginx-network:
      driver: bridge
    mysql-network:
      driver: bridge
    mail-network:
      driver: bridge
    default:
      external:
        name: bridge